CC = gcc
CFLAGS= -g -Wall

all: as client tgt serveur

as:
	$(CC) $(CFLAGS) -o as as.c
client: 
	$(CC) $(CFLAGS) -o client client.c
tgt: 
	$(CC) $(CFLAGS) -o tgt tgt.c
serveur: 
	$(CC) $(CFLAGS) -o serveur serveur.c


